### ISSUE TITLE
Can't be used, it must require macOS 13+

### ISSUE THREAD

**Issue by BerBai** [LeeeSe/MessAuto#1]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/35793154/207811115-df949774-1d55-431d-a17e-95285aeb209d.png">

**Comment by LeeeSe** [comment]
Sorry, I'm just a software development newbie, let me try to find out why

**Comment by LeeeSe** [comment]
Of course you can also compile your own copy on your platform, which takes less than a few minutes

**Comment by LeeeSe** [comment]
Please try v0.2.0 , I replaced many crates and it may solve the problem, but I don't have a version other than macOS13, so please test it yourself

**Comment by chenn1u** [comment]
我在 macOS 10.15.7 下编译的，你可以试试。
https://1drv.ms/u/s!AjbVwdj7IR4tixzFkwif49NXmDtV?e=hlipYg

**Comment by LeeeSe** [comment]
@chenn1u 经过测试在 macOS13 下没有问题
如果不介意的话，邀请你作为项目的协作者以发布 release

**Comment by DavidChenDaivd** [comment]
> 我在 macOS 10.15.7 下编译的，你可以试试。
> https://1drv.ms/u/s!AjbVwdj7IR4tixzFkwif49NXmDtV?e=hlipYg

老哥这个链接好像失效了

**Comment by LeeeSe** [comment]
release 界面这位老哥上传过新版本的，不过最新的暂时还没有
[链接在这里](https://github.com/LeeeSe/MessAuto/releases/tag/v0.2.1)

**Comment by LeeeSe** [comment]
暂时不清楚为何在某版本系统下编译的 app 只能用在相同或更高版本的系统，有没有老哥提供点线索？

**Comment by LeeeSe** [comment]
使用 Github Action 作为临时方案解决
