### ISSUE TITLE
macOS 13 不能正常工作

### ISSUE THREAD

**Issue by sologuy** [LeeeSe/MessAuto#10]
MacBook Pro M1 Pro 
macOS 13.3 (22E252)
![image](https://github.com/LeeeSe/MessAuto/assets/21060714/00445ef2-b626-4b5d-bcaf-38bcfdbf3c4e)
阿里云短信验证码，【阿里云】尊敬的用户：您的校验码：361801，工作人员不会索取，请勿泄漏。
不会自动复制，也不会自动粘贴
请帮忙看一下，谢谢！

**Comment by LeeeSe** [comment]
测试成功，无法复现，问题可能出在权限问题上

**Comment by sologuy** [comment]
> 测试成功，无法复现，问题可能出在完全磁盘访问权限问题上（不过没有权限按理说是打不开软件的），请尝试删除 Messauto 的权限并重新赋予。 下个版本会添加日志系统以方便定位问题

重装一下，可以了，谢谢
