### ISSUE TITLE
建议添加 flags 关键词

### ISSUE THREAD

**Issue by m0cun** [LeeeSe/MessAuto#11]
翻了一下历史短信验证码记录，其中有几条是这样的，感觉有可能会匹配不上：

【Microsoft】将xxxxxx用作Microsoft账户安全代码

【APPLE】Apple ID 代码为：XXXXXX。请勿与他人共享。

**Comment by LeeeSe** [comment]
好的，下个版本允许自定义关键词

**Comment by LeeeSe** [comment]
请尝试最新版本，两例已通过测试
