### ISSUE TITLE
希望增加 macOS 上 Homebrew 包管理器安装方式的支持

### ISSUE THREAD

**Issue by Mrered** [LeeeSe/MessAuto#12]
这里有一个国人维护的小小的 [Homebrew](https://brew.sh/) 包管理器安装脚本仓库，我在对方仓库开了 [issue](https://github.com/ivaquero/homebrew-chinese/issues/17) 。

[Cask Cookbook — Homebrew Documentation](https://docs.brew.sh/Cask-Cookbook) 是 Homebrew 官方提供的 Ruby 脚本编写指南。

感谢作者！

**Comment by Mrered** [comment]
已第三方支持

```sh
brew tap ivaquero/chinese
brew update
brew install messauto
```

**Comment by LeeeSe** [comment]
感谢支持，目前还没有解决 Apple  开发者证书问题，所以暂时还没有向 homebrew 官方提PR

**Comment by Mrered** [comment]
> 第三方实现（我实现的
> 
> ```sh
> brew tap brewfroge/chinese
> brew install messauto
> ``` 

 _Originally posted by @Mrered in [#33](https://github.com/LeeeSe/MessAuto/issues/33#issuecomment-3205777278)_
