### ISSUE TITLE
自动回车 如何启动

### ISSUE THREAD

**Issue by wiihunting** [LeeeSe/MessAuto#13]
自动回车：自动粘贴的更进一步，只有自动粘贴功能启用，自动回车功能才可以被选中
-- 请问 自动粘贴功能 如何启动呢？😂

**Comment by LeeeSe** [comment]
点击图标，列出菜单，手表左键点击即可勾选你喜欢的选项，这里的逻辑很难理解吗？如果是的话会考虑修改

**Comment by wiihunting** [comment]
<img width="171" alt="iShot_2023-06-03_23 03 13" src="https://github.com/LeeeSe/MessAuto/assets/2383622/e0449c08-995e-48fb-90c4-56db8e2b6ea6">
这个我当然是知道的，我的问题是，我点选自动回车后，在实际操作中并没有自动回车。
看到您的说明是需要启用 自动粘贴功能，-- 说到这儿我忽然明白你的意思了。
其实是菜单选项中，只有先启用第一项自动粘贴，才能启用第二项自动回车功能 😂

好吧，明白了。因为自动回车功能没有生效，我以为自动粘贴功能需要在系统设置的哪里打开呢。

所以还是这个问题：我经常用国税网页版，需要填写验证码。现在可以实现自动粘贴，但不能实现自动回车（两项都已勾选）

**Comment by wiihunting** [comment]
again，谢谢您的认真回复。
-- 现在这种态度真是不多见了呢

**Comment by LeeeSe** [comment]
某些网页并不支持回车确认，这是已知问题，不过并不是 messauto  的问题，是网页开发者本身没有给按钮绑定快捷键，这个问题暂时没有解决办法，实际上系统已经尝试按了一下回车键，你可以尝试手动回车，应该也不会有反应（应该

**Comment by wiihunting** [comment]
好的，感谢耐心回复
