### ISSUE TITLE
提取验证码的规则可以再完善一些

### ISSUE THREAD

**Issue by lazygoat644** [LeeeSe/MessAuto#14]
有的短信不只有验证码的一串数字，也包括其他数字，这会影响验证码的提取，建议优先匹配 8、6、4 位的数字作为验证码，或者通过其他方式。

例如：
【自如网】自如验证码 356407，有效时间为一分钟，请勿将验证码告知任何人！如非您本人操作，请及时致电4001001111

**Comment by LeeeSe** [comment]
请尝试最新版本，此例已通过测试

**Comment by Demon95** [comment]
看了下当前版本的处理方式

> // 如果信息中包含多个4-7位数字与字母组合（比如公司名称和验证码都是4-7位英文数字组合，例如CSDN）
> // 则选取数字字符个数最多的那个字串作为验证码

【自如网】自如验证码 356407，有效时间为一分钟，请勿将验证码告知任何人！如非您本人操作，请及时致电**1234567**
像这样的用例会误提取7位固话号码, 感觉可以采纳这位老哥的建议, 即

> 优先匹配 8、6、4 位的数字作为验证码

或者考虑开放配置给用户?
