### ISSUE TITLE
macOS 13.4下了arm架构的版本，磁盘和辅助都开了，还是没用啊

### ISSUE THREAD

**Issue by Fori-designer** [LeeeSe/MessAuto#17]

**Comment by gaoyuanzong** [comment]
+1 
给了磁盘权限，然后打开还是提示需要

**Comment by yujianet** [comment]
我也是。。

我的环境是MBA 15寸、M2芯片，13.5.2版本；

我操作顺序是这样的：打开app，提示给磁盘权限，添加权限后再次启动app，然后打开自动填充，提示要辅助功能，给与辅助功能后手动退出app，然后再打开app，无响应。

无响应期间我检查进程列表，发现MessAuto进程100%cpu占用，kill掉后，重新打开，最后就好了。

**Comment by LeeeSe** [comment]
增加了日志功能，可以初步判断是哪里出了问题，路径“~/.config/messauto/messauto.log”
