### ISSUE TITLE
Hidden by bartender4, MessAuto's menubar icon goes to overlap the Apple icon at the topleft.

### ISSUE THREAD

**Issue by womeimingzi11** [LeeeSe/MessAuto#18]
As the title said. The solution is open MessAuto and then close the main panel. Other applications do not have this issue yet.
Bartender4's version is 4.2.21 (The latest)
My OS version is Sonoma (23A5337a, The latest).

**Comment by LeeeSe** [comment]
Purposely downloaded Bartender4 and didn't find the problem you mentioned
14.0 Beta(23A5337a)
<img width="441" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/44465325/0bbf0f3f-a7e8-477c-8b7d-a7436641bde4">

**Comment by womeimingzi11** [comment]
Weird. This issue is very common on my computer, maybe I can try to take a screenshot.

发件人: LeeeSe ***@***.***>
日期: 星期一, 2023年9月11日 12:53
收件人: LeeeSe/MessAuto ***@***.***>
抄送: 我是洗衣机 ***@***.***>, Author ***@***.***>
主题: Re: [LeeeSe/MessAuto] Hidden by bartender4, MessAuto's menubar icon goes to overlap the Apple icon at the topleft. (Issue #18)

Purposely downloaded Bartender4 and didn't find the problem you mentioned
14.0 Beta(23A5337a)
[image]<https://user-images.githubusercontent.com/44465325/266910985-0bbf0f3f-a7e8-477c-8b7d-a7436641bde4.png>

―

**Comment by womeimingzi11** [comment]
Here is the screenshot.
![](https://cdn.jsdelivr.net/gh/womeimingzi11/self-image@image-storage/202309180857189.png)

**Comment by LeeeSe** [comment]
Does this problem still exist if bartender4 is turned off?

**Comment by womeimingzi11** [comment]
Yes. Even I turn the bartender4 off, and then turn it on, this overlap icon will dismiss too.

发件人: LeeeSe ***@***.***>
日期: 星期一, 2023年9月18日 09:02
收件人: LeeeSe/MessAuto ***@***.***>
抄送: 我是洗衣机 ***@***.***>, Author ***@***.***>
主题: Re: [LeeeSe/MessAuto] Hidden by bartender4, MessAuto's menubar icon goes to overlap the Apple icon at the topleft. (Issue #18)

Does this problem still exist if bartender4 is turned off?

―

**Comment by LeeeSe** [comment]
你的意思是无论是否打开bartender4，MessAuto 的图标始终会与 Apple 图标重叠？

**Comment by womeimingzi11** [comment]
No, once I quit bartender4, icon goes well. After then, when I opened bartender4 again, it still goes well. The issue looks only happen when I boot or reboot my computer.

发件人: LeeeSe ***@***.***>
日期: 星期一, 2023年9月18日 09:08
收件人: LeeeSe/MessAuto ***@***.***>
抄送: 我是洗衣机 ***@***.***>, Author ***@***.***>
主题: Re: [LeeeSe/MessAuto] Hidden by bartender4, MessAuto's menubar icon goes to overlap the Apple icon at the topleft. (Issue #18)

Do you mean that the MessAuto icon will always overlap the Apple icon whether bartender4 is open or not?

―

**Comment by LeeeSe** [comment]
same as #26
