### ISSUE TITLE
打开自动粘贴功能后，在Safari下经常失效

### ISSUE THREAD

**Issue by wisinfun** [LeeeSe/MessAuto#19]
![image](https://github.com/LeeeSe/MessAuto/assets/41355260/a0a2e498-0bdf-4229-a4eb-21300e16c982)
这是这样的状态，不知道是输入法的问题，还是Safari的问题，其他浏览器正常

建议增加一个忽略清单，在忽略清单里，不触发自动粘贴

**Comment by LeeeSe** [comment]
可能是 cmd 和 v 之间的时间间隔太短，导致 cmd 被按下这个事件被操作系统忽略，而v键被按下这个事件被操作系统捕获，进而出现了 v 字符被打出来，按理说 cmd + v 是一个粘贴的行为，不应该有任何字符被打出来。

这两天会发布新版本，你说的这个问题将一并被处理，感谢反馈。

**Comment by LeeeSe** [comment]
请下载新版本测试，情况可能会好一些

**Comment by wisinfun** [comment]
<img width="260" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/41355260/2c627d60-e983-4d2e-adf9-e24db44b68bb">
MacOS 13.5.2

**Comment by LeeeSe** [comment]
这是已知问题，今天利用 Github Action 解决了 macOS 的版本问题，最新 release 在 macOS 11 及以上的系统中应该不会再报错

**Comment by wisinfun** [comment]
Safari下测试了几次都正常了，感谢
