### ISSUE TITLE
是否只支持中文

### ISSUE THREAD

**Issue by romantech** [LeeeSe/MessAuto#2]
您好，我想问一下两点。

我是非中文用户，所以在iMessage上收到的短信内容上不会包含中文“验证”这两个字。
刚刚下载试了一下可惜没反应。是不是跟这点有关。

我看了一下代码发现如下
https://github.com/LeeeSe/MessAuto/blob/180f7a57dc5e5dcbf0e32a74d3919a7fb0f47643/src/main.rs#L18
是不是把flag变量值改成其他value比如`verification`等等就可以用了

另外一问题是 /Users/ls... 路径的`ls`是不是需要改成自己电脑的用户名
https://github.com/LeeeSe/MessAuto/blob/180f7a57dc5e5dcbf0e32a74d3919a7fb0f47643/src/main.rs#L62
或者是不是需要改成 `.arg("~/Library/Messages/chat.db")`

**Comment by LeeeSe** [comment]
是的，需要一个触发关键词，你可以根据你的信息中的关键词来修改；
另外路径确实有问题，我昨天回滚了一次代码，这里忘了再改成最新的。
我稍等会提交一份 0.1.2 版本，解决你所说的问题

我是新手程序员，技术不是很到位，请你包容一下，感谢你的反馈。

**Comment by romantech** [comment]
感谢快速回复，我也是个新手，而且我没学过Rust所以完全看不懂 😢
请您多多关照 :)

**Comment by LeeeSe** [comment]
请问英文验证码中常常包含“verification” 单词吗？还有其他情况吗？比如“Verification”或者“VERIFICATION”
以及验证码是4-6位纯数字还是带数字与字母混搭。
我昨天发现了有6位数字与字母混搭的验证码

**Comment by LeeeSe** [comment]
英文环境验证码提取应该要比中文复杂一些，尤其是验证码为字母数字混合的情况，如果你愿意花些时间收集一下各种验证码的类型并反馈到，我很乐意增添算法来使软件适用于英文环境。

我的邮箱：zlsender@163.com

**Comment by romantech** [comment]
我是韩语用户，韩语的话一般短信内容包含`인증`(认证)这个单词
英语如果需要考虑大小(Capitalization)的话可以使用[ToUppercase](https://doc.rust-lang.org/stable/std/char/struct.ToUppercase.html)method。
我觉得不用搜集所有类型，可以先以verification等几个代表性单词来触发关键词

**Comment by LeeeSe** [comment]
根据你的反馈做了四点改进：
- 初步支持 中文、英语、韩语
- 支持提取 4-6 位数字和字母组合的验证码类型
- 若来信的公司名称也为 4-6 位数字和字母组合，与验证码类似，则会进行简单判断
- 更改为自动获取用户目录

**Comment by romantech** [comment]
我刚试了一下，可以正常使用了（测试了韩语）
棒棒

**Comment by LeeeSe** [comment]
能给大家带来一些便捷是我的荣幸。
另外能否提供你的 Mac 系统版本号，上一个 issue 中有人提到无法用于 macOS13 之外的版本

**Comment by romantech** [comment]
> 

Ventura 13.1
