### ISSUE TITLE
macOS 10 11 12系统太惨了

### ISSUE THREAD

**Issue by androidcn** [LeeeSe/MessAuto#20]
macOS 10 11 12系统太惨了

**Comment by LeeeSe** [comment]
我是macOS14 编译的，按理说macOS13也不能用
等我用Github Action编译试试

**Comment by LeeeSe** [comment]
已发布新 release，macOS 11 及以上应该不会再报错

**Comment by androidcn** [comment]
> 已发布新 release，macOS 11 及以上应该不会再报错

谢谢 终于可用了。我测试一下
