### ISSUE TITLE
开启自动回车后，偶尔关闭chrome页面后会再次打开此页面

### ISSUE THREAD

**Issue by pencilheart** [LeeeSe/MessAuto#22]
关闭自动回车功能后无此问题

**Comment by LeeeSe** [comment]
比较难猜测原因，MessAuto 自动回车只是模拟用户按下了 enter 键，其他什么都没做，可能在那会儿你键盘上的 Meta 键刚好被按下，且

**Comment by pencilheart** [comment]
您说得对。这个issue发生在从页面1打开页面2后，关闭页面2，将会在页面1原有光标处点击enter从而重新打开页面2。不知是哪个地方误触发了自动回车？在此期间并无发送或者收取验证码。

**Comment by LeeeSe** [comment]
短信数据库更新会触发检测最近一分钟内短信行为，我开发的时候发现即使只收到一次短信，但 Chat.db 文件会更新多次，于是就多次进行了短信检测行为，导致多次的复制粘贴，我当时在每次检测中间加了 1 秒的延迟以消除这种干扰，看来加的延迟还是太短了

**Comment by pencilheart** [comment]
有可能，我也是偶然遇到的，后面重新开启后也没有出现此问题了。可以试试改进下再看看后续有没有此问题。感谢。
