### ISSUE TITLE
可否设置为不自动粘贴，但可以在chrome中像safari一样弹出小窗

### ISSUE THREAD

**Issue by pencilheart** [LeeeSe/MessAuto#23]
避免在iphone上需要填充验证码时，mac端也会不必要的输入验证码，造成误输入。

**Comment by LeeeSe** [comment]
有考虑，不过弹出的小窗应该不是类似 Safari 那样的直接定位到输入框的，目前考虑弹出到鼠标指针附近，一是因为我不懂前端，二是因为 MessAuto 不仅仅针对浏览器

**Comment by pencilheart** [comment]
确实是一个极好的软件，也希望可以有更多感兴趣的开发者加入进来，辛苦作者大大了。

**Comment by LeeeSe** [comment]
v0.6.0 中添加了悬浮窗功能，不太完美
