### ISSUE TITLE
软件下载后打不开怎么办？

### ISSUE THREAD

**Issue by yym68686** [LeeeSe/MessAuto#24]
<img width="274" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/31803242/aa0442a4-cbe9-430c-b53c-1c5203786ee4">

系统 mbp m1 pro macos 13.5

**Comment by yym68686** [comment]
仔细看了一下 README ，知道怎么解决了。

**Comment by LeeeSe** [comment]
因为没有 Apple 开发者账户，所以很麻烦
