### ISSUE TITLE
MacOS 14.0左上角有个app图标问题

### ISSUE THREAD

**Issue by li-Coulson** [LeeeSe/MessAuto#26]
您好，我的M1 pro芯片的mac更新了MacOS 14.0之后，左上角有个app图标，且层级在这个苹果图标的上层，导致无法点击设置，您看一下是否有这个问题
<img width="207" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/28707890/2bc1e901-9b57-4e55-9da5-e9cd3db99116">

**Comment by LeeeSe** [comment]
同 #18 ,请问您的 Mac 中是否安装了hide by bartender4?

**Comment by LeeeSe** [comment]
已经反馈给上游仓库，未 PR，期待修复🐶
