### ISSUE TITLE
配置文件自定义关键词被重置

### ISSUE THREAD

**Issue by huwan** [LeeeSe/MessAuto#27]
反馈：自定义了messauto.json里面的关键词，手动更新到0.6.0版本后，发现整个配置文件里面的关键词又变回了默认的，丢失了全部的自定义关键词。

**Comment by LeeeSe** [comment]
很严重的问题，会尽快修复，当时没考虑关键词这条配置

**Comment by LeeeSe** [comment]
丢失的关键词应该无法被找回，但以后不管怎么更新，用户已有的配置不会再被删除，除非某条配置已被弃用，则此条会被删除，其他不变

**Comment by huwan** [comment]
非常感谢开发者。
