### ISSUE TITLE
建议提供 arm64 的编译包

### ISSUE THREAD

**Issue by Kaol-Fu** [LeeeSe/MessAuto#3]
其实提示损坏没关系的，执行命令`xattr -cr /Applications/XXX.app`就能正常使用了，只需要添加个说明告诉 M 系列用户就行了。毕竟安装个语言包再编译有点硬核了

**Comment by LeeeSe** [comment]
好吧，马上添加

**Comment by LeeeSe** [comment]
已上传，请测试，如果有问题烦请反馈

**Comment by Kaol-Fu** [comment]
> 已上传，请测试，如果有问题烦请反馈

已测试通过，谢谢！
