### ISSUE TITLE
悬浮窗功能无法使用，提示无辅助功能权限

### ISSUE THREAD

**Issue by pipipiper** [LeeeSe/MessAuto#31]
如图：
<img width="920" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/80835169/4c1b5919-db4d-4b4d-af84-95ecd158f370">
确认已开启权限：
<img width="715" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/80835169/a0526480-6734-4b5c-aa30-b27e4736b60f">
另外右上角图标日间模式也为黑色，非常的不协调，望修复，万分感谢。
<img width="289" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/80835169/9c082d99-1c64-443c-8757-5b9dfcd4194d">

**Comment by LeeeSe** [comment]
对于第一个问题，我也经常碰到，通常是在软件更新后，需要从辅助功能或者磁盘权限列表中将 MessAuto 手动移除，然后再次请求权限时勾选上才会生效，仿佛新的和旧的是完全不同的两个 App，目前怀疑是使用的权限请求相关依赖库不太完善，我有时间看下依赖库的实现方法

对于第二个问题，我不知道菜单栏 icon 应该用什么格式的图像，看来可能不是 png

**Comment by LeeeSe** [comment]
问题二已修复，等待 GitHub Action 打包 0.6.3 版本 #32

**Comment by pipipiper** [comment]
> 打包

谢谢！问题均已解决，不过这个新的悬浮窗功能为何我尝试command+鼠标左键单机验证码位置并不能自动粘贴，是我操作有问题还是？

**Comment by LeeeSe** [comment]
cmd+click 之前有先单击一下验证码窗口吗？另外 ~/.config/messauto/messauto.log 里显示什么？

**Comment by pipipiper** [comment]
[messauto.log](https://github.com/LeeeSe/MessAuto/files/12998977/messauto.log)

**Comment by LeeeSe** [comment]
刚才试了下是可以的，你有没有把辅助功能权限重新赋予一遍？

这个恼人的问题只会在版本更新时，与我的应用内更新方式有关，我目前初步询问了 Mac 应用内更新的正规方式，但是近期可能没精力重写了

**Comment by pipipiper** [comment]
> 刚才试了下是可以的，你有没有把辅助功能权限重新赋予一遍？
> 
> 这个恼人的问题只会在版本更新时，与我的应用内更新方式有关，我目前初步询问了 Mac 应用内更新的正规方式，但是近期可能没精力重写了

我是直接卸载了重装的，现在自动粘贴可用，但是单击悬浮窗不可用，所以辅助功能应该是没问题的，能否留个邮箱我给您发送个录屏，由于涉及手机号隐私不方便在这里直接贴出。

**Comment by LeeeSe** [comment]
zlsender@163.com

**Comment by LeeeSe** [comment]
看来有必要在文档中添加一个简短的悬浮窗使用教程

**Comment by pipipiper** [comment]
> 看来有必要在文档中添加一个简短的悬浮窗使用教程

看了您的视频，会用了，但是感觉操作有些过于繁琐，其实我个人觉得，不如把这个悬浮窗功能改为发送一条长通知，提示用户用command+v粘贴，或者自定义什么快捷键进行专门的验证码粘贴操作（验证码本身不自动进入剪贴板），像现在这种悬浮窗的方式需要鼠标离开输入框再回来，主要受限于软件本身，悬浮窗并不能像iPhone那样准确的出现在输入框的下部。

**Comment by LeeeSe** [comment]
我不懂前端，不知道如何定位验证码输入框，如果要彻底改变悬浮窗体验，需要一位懂前端的朋友参与

对于长通知问题， iMassage 和 Mail 本身已经具备了，MessAuto 会提前处理好；对于快捷键问题，可能暂时不会考虑，不想再占用用户宝贵的常用快捷键空间，或是增加用户心智负担

我建议用户要么全自动，要么加强悬浮窗体验（只需点一下）
