### ISSUE TITLE
cargo bundle --release报错

### ISSUE THREAD

**Issue by imchenway** [LeeeSe/MessAuto#34]
$ cargo bundle --release

    Updating crates.io index
error: failed to select a version for `gdk-sys`.
    ... required by package `gdk v0.16.0`
    ... which satisfies dependency `gdk = "^0.16"` of package `gtk v0.16.0`
    ... which satisfies dependency `gtk = "^0.16"` of package `libappindicator v0.8.0`
    ... which satisfies dependency `libappindicator = "^0.8"` of package `tray-icon v0.9.0`
    ... which satisfies dependency `tray-icon = "^0.9.0"` of package `MessAuto v0.6.3 (/Users/david/MessAuto)`
versions that meet the requirements `^0.16` are: 0.16.0

the package `gdk-sys` links to the native library `gdk-3`, but it conflicts with a previous package which links to `gdk-3` as well:
package `gdk-sys v0.18.0`
    ... which satisfies dependency `ffi = "^0.18"` of package `gdk v0.18.0`
    ... which satisfies dependency `gdk = "^0.18"` of package `gtk v0.18.1`
    ... which satisfies dependency `gtk = "^0.18"` of package `tao v0.23.0`
    ... which satisfies dependency `tao = "^0.23.0"` of package `MessAuto v0.6.3 (/Users/david/MessAuto)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='gdk-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `gdk-sys` which could resolve this conflict
error: Result of `cargo build` operation was unsuccessful: exit status: 101

**Comment by LeeeSe** [comment]
把 tao 的版本切回 0.22.3，因为和 tray-icon 依赖冲突，tray-icon 下个版本会更新依赖
