### ISSUE TITLE
希望加一个粘贴验证码后触发自定义快捷键的功能

### ISSUE THREAD

**Issue by cat677** [LeeeSe/MessAuto#37]
以方便配合其他第三方自动化工具

**Comment by LeeeSe** [comment]
粘贴之后再触发快捷键吗？我还没能理解需求

**Comment by Apolsus** [comment]
我希望是触发快捷键后再进行监听，这样就不用一直轮询了。
以及设置1分钟后从自动剪贴板删除掉这个验证码的记录。
当然现在已经很棒了，辛苦～

**Comment by LeeeSe** [comment]
MessAuto 只是监听信息数据库是否发生文件变动，在收到新消息之前没有发生任何文件读取的动作，轮询监听的代价很小，只占用 cpu 单核的不到 0.1%，但是可以省去手动触发的麻烦

你说的 1 分钟后从剪贴板删掉验证码这点将会作为可选功能添加到下个版本
