### ISSUE TITLE
希望可设置关闭日志

### ISSUE THREAD

**Issue by Apolsus** [LeeeSe/MessAuto#38]
这个日志会把我的邮件内容搬运到另一个文件存起来，还不是个临时目录。让人感觉非常不安捏。
也许可以在设置里关掉。实现上直接把日志输出路径设置到垃圾目录 `/dev/null` 就好了

**Comment by LeeeSe** [comment]
将改成不记录具体内容，只记录收到了新邮件或信息

**Comment by LeeeSe** [comment]
将更改日志保存目录，不再保存到 .config 文件夹中，以避免上传 config 时泄露隐私
