### ISSUE TITLE
希望能够支持隐藏图标,刘海屏的 Mac 图标位十分紧张

### ISSUE THREAD

**Issue by you-hengh** [LeeeSe/MessAuto#4]
希望能够支持隐藏图标,刘海屏的 Mac 图标位十分紧张

**Comment by Kaol-Fu** [comment]
+1，建议默认启用，不然运行之后完全找不到图标启用，得关掉好多程序才能找到图标启用。能添加快捷键启用也不错。

**Comment by LeeeSe** [comment]
请检查 v0.2.0 ,实现了隐藏图标和默认启用，抱歉这是晚来的更新
