### ISSUE TITLE
自动填充手机号并发送验证码

### ISSUE THREAD

**Issue by hillsdong** [LeeeSe/MessAuto#47]
类似密码管理工具一样，可以通过快捷键触发整个登陆流程的自动化执行。

**Comment by LeeeSe** [comment]
好想法，会考虑实现在 2023年12月29日，19:41，Hills ***@***.***> 写道：﻿
类似密码管理工具一样，可以通过快捷键触发整个登陆流程的自动化执行。

**Comment by LeeeSe** [comment]
实现这个需求需要开发浏览器扩展，暂时没有这个计划
