### ISSUE TITLE
打开了自动复制粘贴功能，不过还是希望有忽略Safari浏览器

### ISSUE THREAD

**Issue by wisinfun** [LeeeSe/MessAuto#48]
因为Safari能自动识别验证码，并且选择后，可以自动删除这条短信记录。手机上也不会一直显示未读了。
所以Safari浏览器还是用原生的好一些。

**Comment by LeeeSe** [comment]
1. 检测 Safari 是否处于前台
2. 删除短信记录这个功能暂时没有实现思路，改查信息数据库（无法实现增删，我不会，简单的增删操作无效）并没有影响到信息 APP 中显示的内容
