### ISSUE TITLE
点击启动无反应

### ISSUE THREAD

**Issue by reycn** [LeeeSe/MessAuto#5]
复现步骤：
打开软件 - 状态栏右键图标 - 单击启动，无反应，菜单仍为未启动状态

OS: 13.1 (22C65)
Device: Macbook Air M1 2020
全磁盘访问、辅助权限已授予，可以正常接收短信

**Comment by LeeeSe** [comment]
确定授予两个权限后，可以重启APP并重新点击“启动”
另外程序启动后app菜单不会有任何变化，但其实已经启动了监测短信的线程

**Comment by Apolsus** [comment]
软件没有主动请求权限。。。

**Comment by LeeeSe** [comment]
请尝试v0.2.0，大幅简化了权限请求流程
