### ISSUE TITLE
When Launched - MessageAuto Blocks "Apple Start Logo Top Left Menu Bar'

### ISSUE THREAD

**Issue by zimbow555** [LeeeSe/MessAuto#50]
When launching MessAuto, My Menu Bar (Top Left Apple Logo) is 'obstructed' and wont allow me to press it. When I use your menu- auto hide from Menu, the obstruction disappears.  See screenshot. Apple Logo is not 'correct'. Installed Version - [v0.6.3](https://github.com/LeeeSe/MessAuto/releases/tag/v0.6.3) / Sonoma 14.2.1 (23C71)

![CleanShot 2024-03-01 at 17 54 42@2x](https://github.com/LeeeSe/MessAuto/assets/161874110/a51682f8-34b0-4187-9408-a595421c16f3)

**Comment by LeeeSe** [comment]
This is a known issue with upstream repository that was fed back a long time ago and has not been officially fixed yet
