### ISSUE TITLE
验证码识别错误

### ISSUE THREAD

**Issue by Apocalypsor** [LeeeSe/MessAuto#54]
短信是
```
Citi ID Code: 12345678 We'll NEVER call or text for this code.
```

只识别到了`1234567`

这里只识别到7位了
https://github.com/LeeeSe/MessAuto/blob/b113c9355f584952030ab7099248542cf7e126ea/src/lib.rs#L313

**Comment by LeeeSe** [comment]
感谢反馈，因为我很少有国外验证码的使用经验
