### ISSUE TITLE
Support for emails from Slack

### ISSUE THREAD

**Issue by Ge0rges** [LeeeSe/MessAuto#59]
Hello,

Thanks for a great tool. Just wanted to point out that autofill did not work in Firefox on the slack website from a slack email in the Apple Mail client.

Thanks!

**Comment by LeeeSe** [comment]
Hello, I have never used Slack before. After creating an account just now, I found that it seems like I need another person to add my Slack account and send me a message for me to receive the corresponding email. Therefore, it's difficult for me to test on my own. 

From a theoretical standpoint, MessAuto checks all emails sent to any mail.app, whether it's Gmail or Slack Mail. If the email contains the keyword "code", it will then extract the verification code within. I'm not quite sure what you mean by the automatic filling function not working? Is it unable to complete the paste and enter action, or is it completely unable to detect the verification code in the mailbox? 

Can you share the logs here? After clicking the icon, you can see the log options.

**Comment by Ge0rges** [comment]
Hi @LeeeSe 

I turned on "hide forever" and can't find a way to get it back to see the logs. Here's the format of the slack mail. I also attached the login HTML.

Subject line: Slack confirmation code: RKJ-YP6
Body:

<img width="610" alt="Screenshot 2024-03-19 at 12 51 25" src="https://github.com/LeeeSe/MessAuto/assets/3957136/d0fcb1ab-b29a-4cb2-9c27-84705a16dcfc">
<img width="610" alt="Screenshot 2024-03-19 at 12 51 25" src="https://github.com/LeeeSe/MessAuto/assets/3957136/9a6ee859-547a-4518-81f1-b50b374a31c1">

**Comment by LeeeSe** [comment]
I understand that this captcha format is not yet supported because it includes the character "-".

I will address this issue, but not immediately, as there are currently many issues that need to be resolved all at once, including the peculiar logic for hiding icons (this is because the early versions of MessAuto did not intend to add a GUI, hence the rather odd logic for hiding icons).

**Comment by Ge0rges** [comment]
Thank you, no rush.

**Comment by LeeeSe** [comment]
https://github.com/LeeeSe/MessAuto/blob/0c91c305dc0411034e270ea38c11843885fe2261/tests/lib_tests.rs#L113C1-L115C35
