### ISSUE TITLE
没有成功使用

### ISSUE THREAD

**Issue by Big-tao** [LeeeSe/MessAuto#6]
大牛，为啥终端输入了代码，没有效果；是要每次收短信都要点击一次启用吗？

**Comment by LeeeSe** [comment]
使用流程：
- 下载软件并拖拽到应用程序文件夹中
- 终端执行`xattr -cr /Applications/MessAuto.app`
- 打开系统设置，手动赋予完全磁盘访问权限和辅助功能权限
- 打开软件，没有任何界面但任务栏中会出现图标
- 点击图标选择开启

**Comment by LeeeSe** [comment]
开机后在菜单栏中启动一次即可，如果不关机则只需开启一次
