### ISSUE TITLE
v0.7.0版本在macOs v13.6.3 (22G436)（intel处理器）系统中无效

### ISSUE THREAD

**Issue by xmskying** [LeeeSe/MessAuto#60]
上个版本可以实现自动填充并回车，最新版本则没有自动执行上述操作。
可以回退版本，不强制提示更新吗？

配置：
{
"auto_paste": true,
"auto_return": true,
"hide_icon_forever": false,
"launch_at_login": true,
"flags": [
"验证码",
"动态密码",
"verification",
"code",
"인증",
"代码"
],
"listening_to_mail": true,
"float_window": false
}

附日记：
09:54:39 [INFO] Log initialization completed
09:54:39 [INFO] Detect and set App language to: zh-CN
09:54:39 [INFO] 成功获取磁盘访问权限
09:54:40 [INFO] 最新版本号: 70
09:54:40 [INFO] 当前版本号: 70
09:54:40 [INFO] 最新版本号: 70
09:54:40 [INFO] 当前版本号: 70
09:54:40 [INFO] 当前已是最新版本
09:54:54 [INFO] 启用自动回车
09:56:33 [INFO] 悬浮窗开启
09:57:20 [INFO] 检测到新的验证码类型信息
09:57:20 [INFO] 所有可能的验证码为:["896256"]
09:57:20 [INFO] 提取到真正的验证码:"896256"
09:57:44 [INFO] 悬浮窗关闭
14:05:36 [INFO] 检测到新的验证码类型信息
14:05:36 [INFO] 所有可能的验证码为:["127488"]
14:05:36 [INFO] 提取到真正的验证码:"127488"
14:05:36 [INFO] 执行粘贴验证码
14:05:37 [INFO] 执行回车

**Comment by LeeeSe** [comment]
升级操作写死在程序里了，你可以下载旧版本然后禁用它的联网权限

**Comment by LeeeSe** [comment]
0.8禁用了自动更新
