### ISSUE TITLE
不能自动粘贴，但已经复制在粘贴板上了

### ISSUE THREAD

**Issue by winterwd** [LeeeSe/MessAuto#65]
13:53:05 [INFO] 检测到新的验证码类型信息
13:53:05 [INFO] 所有可能的验证码为:["390661"]
13:53:05 [INFO] 提取到真正的验证码:"390661"
13:53:05 [INFO] 执行粘贴验证码

需要手动 CMD+V 才粘贴

自动粘贴已勾选
年前的版本还好好的，最近更新了就不行了
{
    "auto_paste": true,
    "auto_return": false,
    "hide_icon_forever": false,
    "launch_at_login": true,
    "flags": [
        "验证码",
        "verification",
        "code",
        "인증",
        "代码"
    ],
    "listening_to_mail": false,
    "float_window": false,
    "recover_clipboard": false
}

**Comment by winterwd** [comment]
补充：最新版本 0.8.1 出现以上问题，系统是 intel 12.7.3

**Comment by LeeeSe** [comment]
是偶尔无法粘贴还是所有情况都无法粘贴？

**Comment by LeeeSe** [comment]
Mac 的键鼠模拟特别奇怪，经常会被无缘无故吞掉，不是库的问题

**Comment by skyecx** [comment]
同上情况，会到剪贴板，m1, 14.4 (23E214)

**Comment by skyecx** [comment]
每次都无法自动填充，开启悬浮窗点击验证码也无法自动填充，MessAuto已经是必备软件，请大佬关注。
11:39:43 [INFO] Log initialization completed
11:39:43 [INFO] Detect and set App language to: zh-CN
11:39:43 [INFO] 成功获取磁盘访问权限
11:43:27 [INFO] 禁用自动回车
11:43:36 [INFO] 悬浮窗开启
11:45:08 [INFO] 检测到新的验证码类型信息
11:45:08 [INFO] 所有可能的验证码为:["389818"]
11:45:08 [INFO] 提取到真正的验证码:"389818"
11:46:08 [INFO] 检测到新的验证码类型信息
11:46:08 [INFO] 所有可能的验证码为:["454224"]
11:46:08 [INFO] 提取到真正的验证码:"454224"

**Comment by skyecx** [comment]
8.0-8.01版本都尝试过，一样的情况。

**Comment by tanmx** [comment]
最新版 一样的情况

**Comment by douseful** [comment]
上面的，试试在设置里的 隐私与安全性，辅助功能里面把 massAuto - 掉，再重新添加
<img width="827" alt="CleanShot 2024-04-15 at 2 50 27@2x" src="https://github.com/LeeeSe/MessAuto/assets/52767905/16cf5028-b1b9-4a00-bdbd-072983edbdc6">

**Comment by LeeeSe** [comment]
v0.8.2 改为利用 AppleScript 来发送键盘模拟命令，不会再出现这种问题了（大概

**Comment by yslin1995** [comment]
v0.8.2 一样的情况
