### ISSUE TITLE
不占用剪切板有 bug

### ISSUE THREAD

**Issue by Jonas-sci** [LeeeSe/MessAuto#67]
请看日志：
<img width="508" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/66203459/1e3134a8-e8cc-40ff-b85b-b0a4f929e3c3">

我当前的配置如下：
<img width="149" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/66203459/b9b49023-dbc5-4976-8b08-7cb47255b9bb">

**Comment by LeeeSe** [comment]
已修复

**Comment by Jonas-sci** [comment]
v0.8.3 是什么时候发布呢

**Comment by LeeeSe** [comment]
github 正在编译，大概 20 分钟吧
