### ISSUE TITLE
v0.8.3 自动粘贴和自动回车失效 

### ISSUE THREAD

**Issue by rational-stars** [LeeeSe/MessAuto#68]
<img width="340" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/52ef9f34-174e-444a-87e8-e036d74e612f">
系统版本
<img width="479" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/e0fa4a8b-bc6a-4a4a-b3f4-5bab1345bc42">

不能粘贴的网站：我测试的是小红书登录页和知乎登录页 因为这都是我之前使用 能正常自动粘贴和自动回车的

电脑也重启了 app 也多次重启
也给了完全磁盘访问权限  辅助功能
问题是验证码已经在粘贴板中 但不会自动粘贴
<img width="720" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/9e3cb40f-b2e7-4e4d-af97-1ad3f5fae840">
也开启了自动粘贴 也重启了
<img width="163" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/f083e007-920f-45bd-91a4-4a83c197f76d">
配置
<img width="1139" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/0d3be2f9-39a4-43ec-9fc6-a3c96f52d59a">
日志
<img width="650" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/65513250/5eb6f85a-bace-4ed3-a59d-96f5c33f7658">

**Comment by LeeeSe** [comment]
<img width="827" alt="image" src="https://github.com/LeeeSe/MessAuto/assets/44465325/c0c2c26b-1fe3-468c-8b78-29daca7169d7">

确保 MessAuto 具备自动化权限，目前 MessAuto 利用 applescript 来模拟键盘输入

**Comment by rational-stars** [comment]
> <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/44465325/328384937-c0c2c26b-1fe3-468c-8b78-29daca7169d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjMxNTAsIm5iZiI6MTcxNTA2Mjg1MCwicGF0aCI6Ii80NDQ2NTMyNS8zMjgzODQ5MzctYzBjMmMyNmItMWZlMy00NjhjLThiNzgtMjlkYWNhNzE2OWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYWQ2YjQzYjU1OGJjMzExNGYwZTQxNDE2ZWM4MzBjMWQ0ZDI5OTE1MDQzYTQ4ODYwMmQyZjMzZmJmZjQ0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLjUSFN-1sZdXD88rRWM7r0ExWPMH0A5oDShmZO5i0A">
> 确保 MessAuto 具备自动化权限，目前 MessAuto 利用 applescript 来模拟键盘输入

感谢解答 我看了我的 是没有自动化权限 我重新安装 MessAuto 也没有询问我需要自动化权限 我百度搜了 也没有主动添加自动化权限的步骤。我现在该怎么办

**Comment by LeeeSe** [comment]
下载最新版本 v0.8.4， GitHub Action 正在编译中，这个权限只能由程序主动获取，用户无法直接授予，在最新版本中通过勾选自动粘贴选项来触发自动化权限请求

**Comment by rational-stars** [comment]
> 如果有效烦请结束 issue

不好意思 前几天没看见  解决了 在 0.84 版本恢复了 正常访问获取权限  作者解决问题很积极  点个赞
