### ISSUE TITLE
v0.8.3开启监听邮件会导致线程崩溃？

### ISSUE THREAD

**Issue by ops-xu** [LeeeSe/MessAuto#69]
开启邮件监听后，短信监听日志也不打了，不知道是不是把短信的线程给崩了。
![CleanShot 2024-05-07 at 10 16 28](https://github.com/LeeeSe/MessAuto/assets/28681228/562077b3-4d27-4a1b-a1e8-d621b2a393a4)

**Comment by ops-xu** [comment]
好像是偶发性的线程崩溃，我又试着先开启邮件监听，然后重启app，然后再关闭邮件监听，再开启，都没有问题了。应该跟配置无关，可能只是线程的问题。

**Comment by LeeeSe** [comment]
请问你说的短信线程崩溃是如何判断出来的？是无法再提取来自信息 app 的验证码了吗？

**Comment by ops-xu** [comment]
> 请问你说的短信线程崩溃是如何判断出来的？是无法再提取来自信息 app 的验证码了吗？

是的，现象就是无法提取，且短信和邮件的日志都不再打印。
